const MIMO_ENDPOINT = "https://opencode.ai/zen/go/v1/chat/completions";
const MIMO_MODEL = "mimo-v2.5";
const MIMO_API_KEY = "sk-tiCmvyYVq8duMmWubkiUXqw2jgacat9FrGamiWhDd87sj92A7cKeaWlGuKqUNPRO";

/**
 * Strips all markdown syntax (MDX, **, [text](url), ### headers, etc.)
 * returning 100% clean plain text suitable for email clients.
 */
export function cleanMarkdownToPlainText(text: string): string {
  let cleaned = text;

  // 1. Remove code blocks
  cleaned = cleaned.replace(/```[a-zA-Z]*\n?([\s\S]*?)\n?```/g, "$1");

  // 2. Convert markdown links: [text](url)
  cleaned = cleaned.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, (_match, label, url) => {
    const trimmedLabel = label.trim();
    if (
      trimmedLabel === url ||
      trimmedLabel.toLowerCase().startsWith("link to") ||
      trimmedLabel.toLowerCase() === "link"
    ) {
      return url;
    }
    return `${trimmedLabel}: ${url}`;
  });

  // 3. Remove bold / strong formatting: **bold** or __bold__
  cleaned = cleaned.replace(/\*\*([^*]+)\*\*/g, "$1");
  cleaned = cleaned.replace(/__([^_]+)__/g, "$1");

  // 4. Remove standalone emphasis asterisks/underscores around words (e.g. *text*)
  cleaned = cleaned.replace(/(^|[^\*])\*([^\*\n]+)\*([^\*]|$)/g, "$1$2$3");
  cleaned = cleaned.replace(/(^|[^_])_([^_\n]+)_([^_]|$)/g, "$1$2$3");

  // 5. Remove markdown headers: # Header -> Header
  cleaned = cleaned.replace(/^#{1,6}\s+/gm, "");

  // 6. Normalize bullet points: * bullet -> - bullet
  cleaned = cleaned.replace(/^[\*\+]\s+/gm, "- ");

  // 7. Clean up double spacing or leftover artifacts
  cleaned = cleaned.replace(/\n{3,}/g, "\n\n");

  return cleaned.trim();
}

export async function generateProposal(
  profileContent: string,
  jobText: string,
  jobTitle?: string,
  jobUrl?: string,
): Promise<string> {
  const systemPrompt = `You are an expert freelance/remote job applicant writing a compelling, customized, direct proposal email to a client or recruiter based on a job post.

CRITICAL FORMATTING RULES:
- Write strictly in 100% PLAIN TEXT as a standard direct email (Subject line, Greeting, concise hook, relevant experience matching their requirements, raw portfolio links, call to action, professional sign-off).
- DO NOT use ANY Markdown, MDX, or HTML syntax.
- NEVER use asterisks for bolding (do NOT write **bold** or *italic*).
- NEVER use markdown link syntax (do NOT write [Link](url)). Write plain URLs directly (e.g. Portfolio: https://example.com).
- Highlight concrete skills, matching past work, and provide direct value.
- Keep it concise, engaging, and action-oriented.`;

  const userPrompt = `CANDIDATE PROFILE DETAILS:
${profileContent}

JOB POSTING:
${jobTitle ? `Title: ${jobTitle}\n` : ""}${jobUrl ? `URL: ${jobUrl}\n` : ""}
Description/Details:
${jobText}

Please generate a top-tier email proposal for this job in pure plain text (no markdown asterisks or link brackets).`;

  const response = await (globalThis.fetch || fetch)(MIMO_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${MIMO_API_KEY}`,
    },
    body: JSON.stringify({
      model: MIMO_MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.7,
      max_tokens: 1500,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`MiMo API returned error (${response.status}): ${errText}`);
  }

  const data = (await response.json()) as any;
  const rawContent = data?.choices?.[0]?.message?.content;
  if (!rawContent) {
    throw new Error("No response content generated by MiMo API");
  }

  // Sanitize and ensure pure plain text email output
  return cleanMarkdownToPlainText(rawContent);
}
